### ISSUE TITLE
Inconsistent spacing between bot messages (Compact Mode)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/slackmagic#5]
In Compact Mode, there is inconsistent spacing between bot messages:

![2014-07-02_12-58-12](https://cloud.githubusercontent.com/assets/53005/3459262/bce146ec-020a-11e4-91c7-d513e3e39b43.png)

This is caused by the fact that some bot messages have the `.first` class applied to them (which includes `margin-top: .7rem;`) while others do not. I'm not sure what's causing that specific inconsistency.

On this same note, it would be nice if when in Compact mode SlackMagic could simply _remove_ the `.first` class from any bot messages, which will help keep things compact (which works well in Compact mode):

![2014-07-02_13-00-18](https://cloud.githubusercontent.com/assets/53005/3459290/141163de-020b-11e4-961b-b7e04800039b.png)

**Comment by jaswrks** [comment]
Thanks for that report. I think it best not to remove any classes because some of those might be queried via JavaScript by Slack; either now or in the future; i.e. the `first` class could be meaningful in JavaScript, not just in the CSS. However, we could override the styling there to make this fit better. I will take a closer look at this again soon.

**Comment by jaswrks** [comment]
@raamdev This should be resolved in the latest dev branch. Please confirm, thanks!

**Comment by raamdev** [comment]
Confirmed. Looks great now. Thanks!

![2014-07-03_12-21-59](https://cloud.githubusercontent.com/assets/53005/3472632/29bbe06a-02ce-11e4-97bc-d12cb4e04623.png)
